services:
  app:
    image: 'jc21/nginx-proxy-manager:2.12.6'
    restart: unless-stopped
    network_mode: host
    dns:
      - 100.100.100.100
      - 1.1.1.1
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - data-volume:/data
      - letsencrypt-volume:/etc/letsencrypt
    environment:
      INITIAL_ADMIN_EMAIL: ${NPM_USER}
      INITIAL_ADMIN_PASSWORD: ${NPM_PASSWORD}

volumes:
  data-volume:
  letsencrypt-volume: